<?php
namespace Libero\RMA\Block\Adminhtml\RequestProduct;
use Magento\Backend\Block\Widget\Grid as WidgetGrid;
class Grid extends \Magento\Backend\Block\Widget\Grid\Extended
{
    protected $_requestProductCollection;

    public function __construct(
        \Magento\Backend\Block\Template\Context $context,
        \Magento\Backend\Helper\Data $backendHelper,
        \Libero\RMA\Model\ResourceModel\RequestProduct\Collection $requestProductCollection,
        array $data = [])
    {
        $this->_requestProductCollection = $requestProductCollection;
        parent::__construct($context, $backendHelper, $data);
        $this->setEmptyText(__("No Request Product Found"));
    }
    protected function _prepareCollection()
    {
        $this->setCollection($this->_requestProductCollection);
        return parent::_prepareCollection(); // TODO: Change the autogenerated stub
    }
    protected function _prepareColumns()
    {
        $this->addColumn(
            'id_request',
            [
                "header"=>__("ID"),
                "index"=> "id_request"
            ]
        );
        $this->addColumn(
            'customer_name',
            [
                "header"=>__("Customer Name"),
                "index"=> "customer_name"
            ]
        );
        $this->addColumn(
            'customer_email',
            [
                "header"=>__("Customer Email"),
                "index"=> "customer_email"
            ]
        );
        $this->addColumn(
            'product_id',
            [
                "header"=>__("Product"),
                "index"=> "product_id"
            ]
        );
        $this->addColumn(
            'reason',
            [
                "header"=>__("Reason"),
                "index"=> "reason",
                'frame_callback' => [$this,'decorateReason']
            ]
        );
        $this->addColumn(
            'resolution',
            [
                "header"=>__("Resolution"),
                "index"=> "resolution",
                'frame_callback' => [$this,'decorateResolution']
            ]
        );
        $this->addColumn(
            'status',
            [
                "header"=>__("Status"),
                "index"=> "status",
                'frame_callback' => [$this,'decorateStatus']
            ]
        );
        $this->addColumn(
            'create_at',
            [
                "header"=>__("Created At"),
                "index"=> "create_at"
            ]
        );
        return parent::_prepareColumns(); // TODO: Change the autogenerated stub
    }
    public function decorateReason($value){
        $class = "grid-severity-notice";
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $modelReason = $objectManager->create('Libero\RMA\Model\RequestReason')->load($value);
        $text =  $modelReason->getData("reason_label");
        return "<span class='$class'>".$text."</span>";
    }
    public function decorateResolution($value){
        $class = "grid-severity-notice";
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $modelResolution = $objectManager->create('Libero\RMA\Model\RequestResolution')->load($value);
        $text =  $modelResolution->getData("resolution_label");
        return "<span class='$class'>".$text."</span>";
    }
    public function decorateStatus($value){
        $class = "grid-severity-notice";
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $modelStatus = $objectManager->create('Libero\RMA\Model\RequestStatus')->load($value);
        $text =  $modelStatus->getData("status_label");
        return "<span class='$class'>".$text."</span>";
    }
}