<?php
namespace Libero\RMA\Block\Adminhtml\RequestStatus;
use Magento\Backend\Block\Widget\Grid as WidgetGrid;
class Grid extends \Magento\Backend\Block\Widget\Grid\Extended
{
    protected $_requestProductCollection;

    public function __construct(
        \Magento\Backend\Block\Template\Context $context,
        \Magento\Backend\Helper\Data $backendHelper,
        \Libero\RMA\Model\ResourceModel\RequestStatus\Collection $requestCollection,
        array $data = [])
    {
        $this->_requestProductCollection = $requestCollection;
        parent::__construct($context, $backendHelper, $data);
        $this->setEmptyText(__("No Status Found"));
    }
    protected function _prepareCollection()
    {
        $this->setCollection($this->_requestProductCollection);
        return parent::_prepareCollection(); // TODO: Change the autogenerated stub
    }
    protected function _prepareColumns()
    {

        $this->addColumn(
            'status_label',
            [
                "header"=>__("Label"),
                "index"=> "status_label",
            ]
        );
        $this->addColumn(
            'email_to_customer',
            [
                "header"=>__("Email to customer"),
                "index"=> "email_to_customer",
                'frame_callback' => [$this,'decorateEmailCustomer']
            ]
        );
        $this->addColumn(
            'email_to_admin',
            [
                "header"=>__("Email to Admin"),
                "index"=> "email_to_admin",
                'frame_callback' => [$this,'decorateEmailAdmin']
            ]
        );
        $this->addColumn(
            'added_by_store',
            [
                "header"=>__("Added by"),
                "index"=> "added_by_store",
                'frame_callback' => [$this,'decorateStore']
            ]
        );
        return parent::_prepareColumns(); // TODO: Change the autogenerated stub
    }
    public function decorateEmailCustomer($value){
        $class = "";
        $text =  "";
        switch ($value){
            case 0:
                $class = "grid-severity-minor";
                $text = "Processing";
                break;
            case 1:
                $class = "grid-severity-notice";
                $text = "Completed";
                break;
        }
        return "<span class='$class'>".$text."</span>";
    }
    public function decorateEmailAdmin($value){
        $class = "";
        $text =  "";
        switch ($value){
            case 0:
                $class = "grid-severity-minor";
                $text = "No";
                break;
            case 1:
                $class = "grid-severity-notice";
                $text = "Yes";
                break;
        }
        return "<span class='$class'>".$text."</span>";
    }
    public function decorateStore($value){
        $class = "";
        $text =  "Default";
        return "<span class='$class'>".$text."</span>";
    }
}