<?php
namespace Libero\Virtual\Block\Adminhtml\Statement;
use Magento\Backend\Block\Widget\Grid as WidgetGrid;

class Grid extends \Magento\Backend\Block\Widget\Grid\Extended
{
    protected $_statementCollection;

    public function __construct(
        \Magento\Backend\Block\Template\Context $context,
        \Magento\Backend\Helper\Data $backendHelper,
        \Libero\Virtual\Model\ResourceModel\Statement\Collection $statementCollection,
        array $data = [])
    {
        $this->_statementCollection = $statementCollection;
        parent::__construct($context, $backendHelper, $data);
        $this->setEmptyText(__("No Statement Found"));
    }

    protected function _prepareCollection()
    {
        $this->setCollection($this->_statementCollection);
        return parent::_prepareCollection(); // TODO: Change the autogenerated stub
    }
    //Show column
    protected function _prepareColumns()
    {
        $this->addColumn(
            'id_statement',
            [
                "header"=>__("ID"),
                "index"=> "id_statement"
            ]
        );
        $this->addColumn(
            'id_customer',
            [
                "header"=>__("ID Customer"),
                "index"=> "id_customer"
            ]
        );
        $this->addColumn(
            'amount',
            [
                "header"=>__("Payment Amount"),
                "index"=> "amount"
            ]
        );
        $this->addColumn(
            'status',
            [
                "header"=>__("Status"),
                "index"=> "status",
                'frame_callback' => [$this,'decorateStatus']
            ]
        );
        $this->addColumn(
            'content',
            [
                "header"=>__("Content"),
                "index"=> "content"
            ]
        );
        $this->addColumn(
            'date_of_pay',
            [
                "header"=>__("Date Of Payment"),
                "index"=> "date_of_pay"
            ]
        );
        return parent::_prepareColumns(); // TODO: Change the autogenerated stub
    }
    public function decorateStatus($value){
        $class = "";
        $text =  "";
        switch ($value){
            case 0:
                $class = "grid-severity-minor";
                $text = "Processing";
                break;
            case 1:
                $class = "grid-severity-notice";
                $text = "Completed";
                break;
        }
        return "<span class='$class'>".$text."</span>";
    }
}