<?php
namespace Libero\Virtual\Block\Adminhtml;

class Statement extends \Magento\Backend\Block\Widget\Grid\Container
{
    protected function _construct()
    {
        $this->_blockGroup="Libero_Virtual";
        $this->_controller="adminhtml_index";
        parent::_construct(); // TODO: Change the autogenerated stub
    }
}
