<?php
namespace Libero\RMA\Block\Adminhtml\RequestCondition;
use Magento\Backend\Block\Widget\Grid as WidgetGrid;
class Grid extends \Magento\Backend\Block\Widget\Grid\Extended
{
    protected $_requestProductCollection;

    public function __construct(
        \Magento\Backend\Block\Template\Context $context,
        \Magento\Backend\Helper\Data $backendHelper,
        \Libero\RMA\Model\ResourceModel\RequestCondition\Collection $requestCollection,
        array $data = [])
    {
        $this->_requestProductCollection = $requestCollection;
        parent::__construct($context, $backendHelper, $data);
        $this->setEmptyText(__("No Request Condition Found"));
    }
    protected function _prepareCollection()
    {
        $this->setCollection($this->_requestProductCollection);
        return parent::_prepareCollection(); // TODO: Change the autogenerated stub
    }
    protected function _prepareColumns()
    {
        $this->addColumn(
            'id_reason',
            [
                "header"=>__("Reason"),
                "index"=> "id_reason",
                'frame_callback' => [$this,'decorateReason']
            ]
        );
        $this->addColumn(
            'id_resolution',
            [
                "header"=>__("Resolution"),
                "index"=> "id_resolution",
                'frame_callback' => [$this,'decorateResolution']
            ]
        );
        $this->addColumn(
            'id_status',
            [
                "header"=>__("Status"),
                "index"=> "id_status",
                'frame_callback' => [$this,'decorateStatus']
            ]
        );
        $this->addColumn(
            'id_package',
            [
                "header"=>__("Package State"),
                "index"=> "id_package",
                'frame_callback' => [$this,'decoratePackage']
            ]
        );
        return parent::_prepareColumns(); // TODO: Change the autogenerated stub
    }
    public function decorateReason($value){
        $class = '';
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $modelReason = $objectManager->create('Libero\RMA\Model\RequestReason')->load($value);
        $text =  $modelReason->getData("reason_label");
        return "<span class='$class'>".$text."</span>";
    }
    public function decorateResolution($value){
        $class = '';
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $modelResolution = $objectManager->create('Libero\RMA\Model\RequestResolution')->load($value);
        $text =  $modelResolution->getData("resolution_label");
        return "<span class='$class'>".$text."</span>";
    }
    public function decoratePackage($value){
        $class = '';
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $modelResolution = $objectManager->create('Libero\RMA\Model\RequestPackage')->load($value);
        $text =  $modelResolution->getData("package_label");
        return "<span class='$class'>".$text."</span>";
    }
    public function decorateStatus($value){
        $class = "grid-severity-notice";
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $modelStatus = $objectManager->create('Libero\RMA\Model\RequestStatus')->load($value);
        $text =  $modelStatus->getData("status_label");
        return "<span class='$class'>".$text."</span>";
    }
}