<?php
namespace Libero\Virtual\Controller\Adminhtml\Index;

use Magento\Backend\App\Action;
use Magento\Backend\App\Action\Context;
use Magento\Framework\View\Result\PageFactory;

class Index extends \Magento\Backend\App\Action
{
    protected $resultPageFactory;
    public function __construct(\Magento\Backend\App\Action\Context $context,\Magento\Framework\View\Result\PageFactory $resultPageFactory)
    {
        parent::__construct($context); // missing wil make error  Uncaught Error: Call to a member function isLoggedIn() on null on admin magento 2
        $this->resultPageFactory = $resultPageFactory;
    }
    public function execute()
    {
        // TODO: Implement execute() method.
        $resultPage = $this->resultPageFactory->create();
        $resultPage->setActiveMenu("Libero_Virtual::index");
        $resultPage->addBreadcrumb(__("Virtual Account"),__("Virtual Account"));
        $resultPage->addBreadcrumb(__("Manager Statement"),__("Manager Statement"));
        $resultPage->getConfig()->getTitle()->prepend(__("Manger Statement"));
        return $resultPage;
    }
    protected function _isAllowed()
    {
        //return parent::_isAllowed(); // TODO: Change the autogenerated stub
        return $this->_authorization->isAllowed('Libero_Virtual::index');
    }
}