<?php
namespace Libero\RMA\Block\Adminhtml;

class RequestProduct extends \Magento\Backend\Block\Widget\Grid\Container
{
    protected function _construct()
    {
        $this->_blockGroup="Libero_RMA";
        $this->_controller="adminhtml_index";
        parent::_construct(); // TODO: Change the autogenerated stub
    }
}
