<?php
namespace Libero\RMA\Controller\Adminhtml\Condition;

use Magento\Backend\App\Action;
use Magento\Backend\App\Action\Context;
use Magento\Framework\View\Result\PageFactory;

class Index extends \Magento\Backend\App\Action
{
    protected $resultPageFactory;
    public function __construct(\Magento\Backend\App\Action\Context $context,\Magento\Framework\View\Result\PageFactory $resultPageFactory)
    {
        parent::__construct($context); // missing wil make error  Uncaught Error: Call to a member function isLoggedIn() on null on admin magento 2
        $this->resultPageFactory = $resultPageFactory;
    }
    public function execute()
    {
        $resultPage = $this->resultPageFactory->create();
        $resultPage->setActiveMenu("Libero_RMA::rma_customfield");
        $resultPage->addBreadcrumb(__("Manage Custom Fields"),__("Manage Custom Fields"));
        $resultPage->getConfig()->getTitle()->prepend(__("Manage Custom Fields"));
        return $resultPage;
    }
    protected function _isAllowed()
    {
        //return parent::_isAllowed(); // TODO: Change the autogenerated stub
        return $this->_authorization->isAllowed('Libero_RMA::rma_customfield');
    }
}