<?php
namespace Libero\RMA\Block\Adminhtml\RequestProduct\Edit;

class Tabs extends \Magento\Backend\Block\Widget\Tabs{

    protected function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
        $this->setId("rma_request_tabs");
        $this->setDestElementId("edit_form");
        $this->setTitle(__("RMA Request"));
    }
    /*protected function _prepareLayout()
    {
        $this->addTab('rmarequest',
            [
                'label' => ("RMA Request"),
                'url' => $this->getUrl('rma/requestproduct/index',['_current' => true]),
                'class' => 'ajax'
            ]
        );
        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }*/

}